server:
  port: 8081
  ####### spring boot mysql connection

spring:
  datasource:
    username: admin
    password: mypassword
    url: jdbc:mysql://database-1.cquzlyntoriy.us-east-1.rds.amazonaws.com:3306/mydb

#    url: jdbc:mysql://localhost:3306/mydb
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
debug: true
